server:
  port: 8080
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service/api/v1/products/**
          predicates:
            - Path=/api/v1/products/**
        - id: product-service-categories
          uri: lb://product-service/api/v1/product-categories/**
          predicates:
            - Path=/api/v1/product-categories/**
        - id: order-service
          uri: lb://order-service/api/v1/orders/**
          predicates:
            - Path=/api/v1/orders/**