server:
  port: 8083
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_test_inventory_service
    username: mmhtoo
    password: mmhtoo@123
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: inventory-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka